### ISSUE TITLE
missing dataset.py

### ISSUE THREAD

**Issue by zhouziyiaichifeiniu** [vnnm404/SaGE#1]
Thanks for the great work!
ReadMe says dataset.py is used to generate MCC dataset from MIC. But I didn't find it in the source code. Could you give some help on this? Thanks!

**Comment by vnnm404** [comment]
Thank you!

Yeah, we removed `dataset.py` from the repo because the full MCC dataset can be found as a csv file. We forgot to remove it from `README.md`, we will fix issues like this. Currently, the readme also claims the `mcc` folder contains the dataset when it does not, this will also be fixed.

The full dataset is available in `data/all/q.csv` where the moral quantifiers are available in `data/all/q_moral.csv`. We will clean up the repo to make it clearer as well. Thanks for raising this issue and if you don't need any more help, I'll close this issue once the fixes have been made. Thanks again!
